[package]
name = "web"
version = "0.1.0"
authors = ["psychoss <626377748@qq.com>"]

[dependencies]
hyper="*"
postgres="*"
time = "*"
rustc-serialize = "0.3.16"
[[bin]]
name = "sever"
path="src/bin/main.rs"
